# Generated by Django 6.0.4 on 2026-04-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
