# Generated by Django 6.0.4 on 2026-04-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_patient_patient_id_alter_healthrecord_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
